name: progweb2

services:
  db:
    image: postgres:17-alpine
    container_name: progweb2_db
    restart: unless-stopped
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - progweb2_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - progweb2_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: progweb2_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - progweb2_network

networks:
  progweb2_network:
    driver: bridge

volumes:
  progweb2_data:

